//Data for dropdown menus for category selection and tags 

export const ingredients = [
    { label: 'Absinthe', value: 'absinthe', parent: 'spirits' },
    { label: 'Apple Juice', value: 'apple_juice', parent: 'mixers' },
    { label: 'Amaretto', value: 'amaretto', parent: 'liqueurs' },
    { label: 'Baileys', value: 'baileys', parent: 'liqueurs' },
    { label: 'Beer', value: 'beer', parent: 'beers' },
    { label: 'Bourbon', value: 'bourbon', parent: 'spirits' },
    { label: 'Champagne', value: 'champagne', parent: 'wines' },
    { label: 'Chocolate Liqueur', value: 'chocolate_liqueur', parent: 'liqueurs' },
    { label: 'Club Soda', value: 'club_soda', parent: 'mixers' },
    { label: 'Cider', value: 'cider', parent: 'beers' },
    { label: 'Coffee Liqueur', value: 'coffee_liqueur', parent: 'liqueurs' },
    { label: 'Cointreau', value: 'cointreau', parent: 'liqueurs' },
    { label: 'Coke', value: 'coke', parent: 'mixers' },
    { label: 'Cranberry Juice', value: 'cranberry_juice', parent: 'mixers' },
    { label: 'Dark Rum', value: 'dark_rum', parent: 'spirits' },
    { label: 'Gin', value: 'gin', parent: 'spirits' },
    { label: 'Ginger Ale', value: 'ginger_ale', parent: 'mixers' },
    { label: 'Lager', value: 'lager', parent: 'beers' },
    { label: 'Lemon Juice', value: 'lemon_juice', parent: 'mixers' },
    { label: 'Lime Juice', value: 'lime_juice', parent: 'mixers' },
    { label: 'Limoncello', value: 'limoncello', parent: 'liqueurs' },
    { label: 'Orange Juice', value: 'orange_juice', parent: 'mixers' },
    { label: 'Orange Liqueur', value: 'orange_liqueur', parent: 'liqueurs' },
    { label: 'Raspberry Syrup', value: 'raspberry_syrup', parent: 'mixers' },
    { label: 'Pineapple Juice', value: 'pineapple_juice', parent: 'mixers' },
    { label: 'Redbull', value: 'redbull', parent: 'mixers' },
    { label: 'Red Wine', value: 'red_wine', parent: 'wines' },
    { label: 'Rum', value: 'rum', parent: 'spirits' },
    { label: 'Sherry', value: 'sherry ', parent: 'wines' },
    { label: 'Soda Water', value: 'soda_water', parent: 'mixers' },
    { label: 'Simple Syrup', value: 'simple_syrup', parent: 'mixers' },
    { label: 'Tequila', value: 'tequila', parent: 'spirits' },
    { label: 'Tonic Water', value: 'tonic_water', parent: 'mixers' },
    { label: 'Triple Sec', value: 'triple_sec', parent: 'liqueurs' },
    { label: 'Vermouth', value: 'vermouth ', parent: 'wines' },
    { label: 'Vodka', value: 'vodka', parent: 'spirits' },
    { label: 'White Rum', value: 'white_rum', parent: 'spirits' },
    { label: 'White Wine', value: 'white_wine', parent: 'wines' },
  ];

  export const options = [
    { label: 'Spirits', value: 'spirits'},
    { label: 'Liqueurs', value: 'liqueurs'},
    { label: 'Wines & Champagnes', value: 'wines'},
    { label: 'Beers & Ciders', value: 'beers'},
    { label: 'Mixers', value: 'mixers'},
];


export const allIngredientArray = [
    'absinthe', 
    'apple_juice', 
     'amaretto',
     'baileys', 
    'beer',
    'bourbon',
    'champagne',
    'chocolate_liqueur',
    'cider', 
    'club_soda',
    'coffee_liqueur', 
    'cointreau', 
    'coke',
    'cranberry_juice',
    'dark_rum', 
    'gin', 
    'ginger_ale', 
    'lager', 
    'lemon_juice', 
    'lime_juice', 
    'limoncello', 
    'orange_juice', 
    'orange_liqueur', 
    'pineapple_juice',
    'raspberry_syrup',
    'redbull', 
    'red_wine', 
    'rum',
    'sherry ', 
    'soda_water', 
    'simple_syrup', 
    'tequila', 
    'tonic_water', 
    'triple_sec',
    'vermouth ',
    'vodka', 
    'white_rum',
    'white_wine',
  ];


  export const filterOptions = [
    { label: 'All', value: null},
    { label: 'Baileys', value: 'baileys'},
    { label: 'Beer', value: 'beer'},
    { label: 'Bourbon', value: 'bourbon'},
    { label: 'Gin', value: 'gin'},
    { label: 'Lime Juice', value: 'lime_juice'},
    { label: 'White Rum', value: 'white_rum'},
    { label: 'Tequila', value: 'tequila'},
    { label: 'Triple Sec', value: 'triple_sec'},
    { label: 'Vodka', value: 'vodka'}
];




